# Generated by Django 4.2.24 on 2025-10-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
