# Generated by Django 4.2.24 on 2025-11-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_categoria_alter_publicacion_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='categories',
        ),
    ]
