# Generated by Django 4.2.24 on 2025-11-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_alter_publicacion_options_alter_publicacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categories',
            field=models.ManyToManyField(to='publicaciones.categoria', verbose_name='Categorias'),
        ),
    ]
