# Generated by Django 4.2.24 on 2025-11-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_publicacion_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='', max_length=100, verbose_name='Descripción'),
        ),
    ]
