# Generated by Django 4.2.24 on 2025-11-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_categoria_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='categories',
            new_name='categorias',
        ),
    ]
